### ISSUE TITLE
None of the examples work

### ISSUE THREAD

**Issue by ejaz-ahmed** [vahidhedayati/testads5#1]
Hi,

I was tired of building auto completes for my domain classes and came up with ads. I have tried examples for 2.4.2 and 2.5.0 but unfortunately none of the examples work. For 2.5.0, when I hit filtering, I get 
```
Error 500: Internal Server Error

URI
    /ajaxdependancyselectexample/myContinent/filteringExamples
Class
    groovy.lang.MissingMethodException
Message
    No signature of method: grails.plugin.ajaxdependancyselection.AutoCompleteService.returnPrimarySearch() is applicable for argument types: (java.lang.String, null, java.lang.String, org.codehaus.groovy.grails.web.taglib.GroovyPageAttributes) values: [, null, ajaxdependancyselectexample.MyCountry, [id:MyCountry11, ...]] Possible solutions: returnPrimarySearch(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
 ```
And the traces on grails stdout are

```
| Error 2015-06-20 15:40:54,132 [http-bio-8080-exec-7] ERROR errors.GrailsExceptionResolver  - MissingMethodException occurred when processing request: [GET] /testads5/myContinent/filteringExamples
No signature of method: grails.plugin.ajaxdependancyselection.AutoCompleteService.returnPrimarySearch() is applicable for argument types: (java.lang.String, null, java.lang.String, org.codehaus.groovy.grails.web.taglib.GroovyPageAttributes) values: [, null, ajaxdependancyselectexample.MyCountry, [id:MyCountry11, ...]]
Possible solutions: returnPrimarySearch(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String). Stacktrace follows:
Message: Error processing GroovyPageView: Error executing tag <g:selectPrimary>: No signature of method: grails.plugin.ajaxdependancyselection.AutoCompleteService.returnPrimarySearch() is applicable for argument types: (java.lang.String, null, java.lang.String, org.codehaus.groovy.grails.web.taglib.GroovyPageAttributes) values: [, null, ajaxdependancyselectexample.MyCountry, [id:MyCountry11, ...]]
Possible solutions: returnPrimarySearch(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
    Line | Method
->>  527 | doFilter  in /var/eejaz/pdev/github/users_rep/testads5/grails-app/views/myContinent/filteringExamples.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Caused by GrailsTagException: Error executing tag <g:selectPrimary>: No signature of method: grails.plugin.ajaxdependancyselection.AutoCompleteService.returnPrimarySearch() is applicable for argument types: (java.lang.String, null, java.lang.String, org.codehaus.groovy.grails.web.taglib.GroovyPageAttributes) values: [, null, ajaxdependancyselectexample.MyCountry, [id:MyCountry11, ...]]
Possible solutions: returnPrimarySearch(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
->>   57 | doCall    in /var/eejaz/pdev/github/users_rep/testads5/grails-app/views/myContinent/filteringExamples.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Caused by MissingMethodException: No signature of method: grails.plugin.ajaxdependancyselection.AutoCompleteService.returnPrimarySearch() is applicable for argument types: (java.lang.String, null, java.lang.String, org.codehaus.groovy.grails.web.taglib.GroovyPageAttributes) values: [, null, ajaxdependancyselectexample.MyCountry, [id:MyCountry11, ...]]
Possible solutions: returnPrimarySearch(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
->>  107 | doCall    in grails.plugin.ajaxdependancyselection.AutoCompleteTagLib$_closure2
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     41 | doCall    in var_eejaz_pdev_github_users_rep_testads5_grails_app_views_myContinent_filteringExamples_gsp$_run_closure2
|     82 | run . . . in var_eejaz_pdev_github_users_rep_testads5_grails_app_views_myContinent_filteringExamples_gsp
|    198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
grails> 
```
I am using compile ":ajaxdependancyselection:0.45-SNAPSHOT2" instead of local path of plugin.

Similar is the case for other actions as well. Can you please verify these examples in a fresh environment?

**Comment by vahidhedayati** [comment]
Hi Ejaz

I presume it is filtering that you are after ? yes it is broke I am trying to figure out what needs changing. Its due to updates in earlier code. You can roll back to 
```
compile ":ajaxdependancyselection:0.39" 
```

Where it was working on that release...

It should also be g:selectPrimary etc not ads: ads is for grails 3. I will update the project  / plugin and let you know when its all working again.

**Comment by vahidhedayati** [comment]
Its now updated and working, trying snapshot3

**Comment by ejaz-ahmed** [comment]
Thanks for the quick updates vahidhedayatii.  Filtering is now working. The other examples also have minor issues. For example, "A No Reference mapping within Auto Complete" only autocompletes continent. Similarly, "Select then Auto complete" does not autocompletes at all. Nested Selection from fully ref to no ref and back to full ref example has two fields with the name "Please choose borough" which do not show any option in dropdown even if I select "Europe United Kingdom and London ".
For "variety" example, example 3, 4 are not working. For "Primary No Ref selection", none of the offices shows up. "Nested Selection from fully fixed search on secondaryNR -" autocompletes country only. 
With the current updates, I am able to move forward with my project. Fixing the concerns I have raised might help me and others to understand the underlying architecture. Hats off for choosing so many example to explain the flexibility which comes with this plugin.

**Comment by vahidhedayati** [comment]
"A No Reference mapping within Auto Complete"  - fixed issue caused by updates to gsps in last release now fixed.

 "Select then Auto complete"  - minor issue with id to id2 in _selectAutoComp.gsp of the plugin now fixed working.


"Nested Selection from fully ref to no ref and back to full ref example" -  a few issues found around the code, reverted to params due to some deeper issues further down in the code.

http://localhost:8080/testads5/myContinent/noRefAutoComplete
http://localhost:8080/testads5/myContinent/norefselection
 both now working

Variety - Example 3 - conflict of used ID names on the same page. working
Example 4 working - try United Kingdom, London, Finance, Dave  (labels are misleading)

Primary No Ref selection - now working on 
http://localhost:8080/testads5/myContinent/selectPrimaryNRFiltering

"Nested Selection from fully fixed search on secondaryNR -" now works - required appendName and appendValue to be added to the other fields... so that when updated the list would give actual results below and once selected the actual real value then other fields updates.

URL for issue mentioned: http://localhost:8080/testads5/myContinent/norefselectSecondaryFilteringFixed

There was a further issue with final road labelled as Vauxhall road, this was not actually bound to camden. I set Abbey road which was.. (all fictional)


Any how I am going to release snapshot4 and update this sample demo project gsp pages. So in effect this project has latest gsp pages tested against latest changes.


Please let me know if anything else is not working or missing from this

**Comment by ejaz-ahmed** [comment]
@vahidhedayati sorry for responding too late this. I am using ads in my application and came up with [this issue](https://github.com/vahidhedayati/ajaxdependancyselection/issues/11). Can you look into it?

**Comment by ejaz-ahmed** [comment]
Thanks for updating the example application. Closing this issue.
